### ISSUE TITLE
attempt to call method 'IsListenServerHost' (a nil value)

### ISSUE THREAD

**Issue by CaiozScripts** [RG-Developers/camcoder#1]
```
[camcoder] addons/camcoder/lua/camcoder/format/preferences.lua:29: attempt to call method 'IsListenServerHost' (a nil value)
    1. Update - addons/camcoder/lua/camcoder/format/preferences.lua:29
        2. unknown - addons/camcoder/lua/camcoder/format/preferences.lua:57
```
Keep getting this when i try to open manager/download/replay/record tabs, only preferences works

**Comment by CaiozScripts** [comment]
Btw it gets stuck like this, like the gui just is there and its stuck
![Tue_Jun_18_23_13_27_2024](https://github.com/RG-Developers/camcoder/assets/117036935/c214dac6-b93f-43ec-8d4a-7db20874bbbb)

**Comment by Def-Try** [comment]
extremely cursed, looks like something broke default gmod functions. are you using latest gmod?

**Comment by CaiozScripts** [comment]
just figured out it was because I was on a outdated version of GMOD. Updated and the gui started working. Thanks
